name: Build and deploy

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push the Docker image
      run: |
        TAG=$(cat deployment/.image_tag)
        docker build . --file Dockerfile --tag "docker.io/cajovahouba/game-triangles:$TAG"
        docker push docker.io/cajovahouba/game-triangles:$TAG

  deploy:
    name: Deploy
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: https://cajova-houba.rocks:6443
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v1
        with:
          namespace: apps
          manifests: |
            deployment/k8s/deployment.yaml
            deployment/k8s/service.yaml